version: "3"

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
